### ISSUE TITLE
Add support for removing all files in dir or clear SPIFFS

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-libs/rpc-service-fs#1]
Would be good to have the ability to clear an entire directory of files (instead of having to do it one by one), or adding a method for calling `mgos_spiffs_erase` for any external flash that has been mounted

**Comment by tripflex** [comment]
Sooooo .. with all the filesystem changes (moving to other libs), the original call that would not remove anything if file system already existed ... IT NOW AUTOMATICALLY FORCES A FORMAT ... IMO it should not be doing this as that is completely opposite of the previous behavior ... took me a minute to figure out why it kept formatting every single time 👎

**Comment by rojer** [comment]
as far as changing the behavior goes - fstab now provides a way to only create filesystem where it's needed, and i found current behavior to be confusing ("why is my system not being created? ahh...") so i flipped it. prior to adding fstab using external filesystems was ratehr cumbersome, so i gather it's not in very widespread use, so this kind of change is a-ok. sorry to hear it caused inconvenience for you...

wrt original issue - no, we're not doing this. wiping a filesystem can be facilitated by reformatting, so this would be redundant. hence, closing this issue.
