### ISSUE TITLE
Document the Dev RPC namespace 

### ISSUE THREAD

**Issue by erfan-azhdari** [mongoose-os-libs/rpc-service-fs#3]
The `Dev` RPC  namespace is undocumented.
it looks like this service also provides some functionality under the Dev namespace they are:

```json
[
  "Dev.Remove",
  "Dev.Erase",
  "Dev.Write",
  "Dev.Read",
  "Dev.Create"
]
```

They are added in `mgos_service_fs.c` line [663](https://github.com/mongoose-os-libs/rpc-service-fs/blob/7edeecacec8ed276aa83485ae8879219dfface29/src/mgos_service_fs.c#L663)

**Comment by rojer** [comment]
actually, i think these should be moved into a separate library.
i only put them there as a quick hack, but forgot to refactor.

**Comment by rojer** [comment]
done, and added short readme - https://github.com/mongoose-os-libs/rpc-service-dev/
